// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/minh1611/clinics_chain_management/mailservice/src/internal/api"
	"github.com/minh1611/clinics_chain_management/mailservice/src/internal/db"
	"github.com/minh1611/clinics_chain_management/mailservice/src/internal/db/psql"
	"github.com/minh1611/clinics_chain_management/mailservice/src/internal/model"
	"github.com/minh1611/clinics_chain_management/mailservice/src/internal/service"
	"github.com/minh1611/clinics_chain_management/mailservice/src/services/authservice"
)

// Injectors from server.wire.go:

func InitMainServer(ctx context.Context, opts ServerOptions) (*Server, error) {
	engine := gin.New()
	dbDsn := opts.DBDsn
	gormDB, err := db.ConnectGorm(dbDsn)
	if err != nil {
		return nil, err
	}
	dbInterfaces := psql.InterfaceProvider()
	serverCDBRepo := &psql.ServerCDBRepo{
		Db:         gormDB,
		Context:    ctx,
		Interfaces: dbInterfaces,
	}
	authServiceAddr := opts.AuthServiceAddr
	authServiceClient, err := authservice.ConnectClient(ctx, authServiceAddr)
	if err != nil {
		return nil, err
	}
	serviceGRPC := authservice.ServiceGRPC{
		Ctx:    ctx,
		Client: authServiceClient,
	}
	serverModel := &model.ServerModel{
		Ctx:  ctx,
		Repo: serverCDBRepo,
		Auth: serviceGRPC,
	}
	userService := &service.UserService{
		Model: serverModel,
	}
	userController := service.UserController{
		S: userService,
	}
	mailservice := &api.mailservice{
		G:    engine,
		User: userController,
	}
	server := &Server{
		ApiServer: mailservice,
		MainRepo:  serverCDBRepo,
	}
	return server, nil
}

// server.wire.go:

type Server struct {
	ApiServer *api.mailservice
	MainRepo  db.ServerRepo
}

type ServerOptions struct {
	DBDsn           db.DBDsn
	AuthServiceAddr authservice.AuthServiceAddr
}
